### ISSUE TITLE
Github Action: IOS Build

### ISSUE THREAD

**Issue by luke-** [humhub/app#11]
e.g. https://medium.com/team-rockstars-it/the-easiest-way-to-build-a-flutter-ios-app-using-github-actions-plus-a-key-takeaway-for-developers-48cf2ad7c72a

**Comment by PrimozRatej** [comment]
How to set up App store connect API:
https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api

**Comment by luke-** [comment]
Ok, should I store the key in the GitHub vault?
