### ISSUE TITLE
IPA Release fail

### ISSUE THREAD

**Issue by luke-** [humhub/app#110]
https://github.com/humhub/app/actions/runs/6164894592/job/16731598861

**Comment by luke-** [comment]
@PrimozRatej Seems it doesn't fixes the problem:
https://github.com/humhub/app/actions/runs/6177310544

**Comment by PrimozRatej** [comment]
For Apple, we need to agree with the new Developer Program Licence Agreement.  This needs to be done by the Account holder here https://appstoreconnect.apple.com/agreements/#/

**Comment by luke-** [comment]
Thanks!
