### ISSUE TITLE
Grey Screen after opening an instance

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/app#117]
Today I upgraded my instance from 1.15.0-beta.1 to beta.2 and the app from 1.0.75 to 1.0.76.
After clearing app data (Android settings) I can’t open my instance anymore. I get a grey screen instead. (I had this problem already with an early app version but it had disappeared.)
I still can open community.humhub.com

Before today's updates it worked fine (but I did not always test with clearing the app data). Only the message count of the app always showed 131 when there was just one (or two) unread notification.

**Comment by luke-** [comment]
Do you get to the login dialog at your instance or do you always get a gray screen right away?

**Comment by felixhahnweilheim** [comment]
I get it right away.

I have tried again with different combinations. It seems the error only occurs with my custom theme, not with the official theme.
(The theme works in the browser and I can’t really imagine what is causing the problem at the moment.)
But feel free to close this issue.

**Comment by ArchBlood** [comment]
> I get it right away.
> 
> I have tried again with different combinations. It seems the error only occurs with my custom theme, not with the official theme.
> (The theme works in the browser and I can’t really imagine what is causing the problem at the moment.)
> But feel free to close this issue.

Could be a view that's not been updated yet?

**Comment by felixhahnweilheim** [comment]
@PrimozRatej humhub.hahn-felix.de
Thanks in advance!

The theme is https://github.com/felixhahnweilheim/humhub-flex-theme/tree/develop

**Comment by PrimozRatej** [comment]
Fix it, the problem was that the app assume the `background_color` and `theme_color` properties from the manifest are in the correct hex format. I now changed it in case it isn't we return primaryColor.

<img width="406" alt="Screenshot 2023-10-11 at 18 56 58" src="https://github.com/humhub/app/assets/10835179/57bf03bc-ae92-46c2-bf6b-8c306fe5dbc4">

**Comment by felixhahnweilheim** [comment]
Thanks a lot! @PrimozRatej
