### ISSUE TITLE
No https

### ISSUE THREAD

**Issue by CyberPingU** [humhub/app#120]
Hello,
while trying to connect to my https://my.example.org I get an error saying that plain text is not allowed: the app infact tries ti connect to http://my.example.org ignoring the "s" of https

**Comment by luke-** [comment]
Please check your Base URL setting: Administration -> Settings.

Also check: https://docs.humhub.org/docs/admin/reverse-proxy

**Comment by CyberPingU** [comment]
Allright,
the base url was correct (https): I added headers passing in the nginx revproxy and now it behaves correctly even from the app.
Sorry for the bother.
The issuse can be closed.
