### ISSUE TITLE
Notification Count 131

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/app#121]
When I get 1 push notification, the app count shows 131 instead of 1.
(When I open the app, only 1 notification is shown.)

(Apart from that the notifications work fine.)

![Screenshot_20231015_091227_One UI Home.jpg](https://github.com/humhub/app/assets/84990763/b54693d5-ee49-4ce1-8ff6-de2df0a6e42d)

app version 1.0.77

Android 13

**Comment by luke-** [comment]
Hmm, I cannot reproduce this.

Steps:

- Closed app, no notification count badge.
- Trigger notification
- Notification received, `1` badge appears
- Click on notification, badge disappers 

---

Btw. we'll plan to sync the HumHub notification count with the App Notification count in the next release: https://github.com/humhub/app/issues/52

**Comment by felixhahnweilheim** [comment]
Hi, I have now also tested with community.humhub.com (luckily someone commented a post, so I got a push notification).
But the notification badge shows again 131.

I have downloaded the app from the Github release (arm64-v8a) version 1.0.77

Android 13

One-UI version 5.1

Samsung Galaxy A51
anything else that could be relevant?

But if you rework the notification count anyway, we can wait for this and I test again with next release.

**Comment by luke-** [comment]
@PrimozRatej Any idea?

**Comment by PrimozRatej** [comment]
I checked the functionality the badge count is set only in 2 cases. 1. The user gets a push notification that contains the badge count.  2. updateNotificationCount Js channel is triggered on the web app, and the count is sent over the JS channel. @felixhahnweilheim  Is it possible you have  `131` unread notifications?

**Comment by felixhahnweilheim** [comment]
I tested with 2 of my installations and also community.humhub.com, always the same number: 131

Now I went again to the debug page of the FCM module and tried out "Test notification count". 
The new number is shown correctly when there is an unread push notification.

After trying that a few times I removed the unread Android notification and tested again.
Now the notification badge shows 1. :-)

So I guess the number 131 was just left over from "Test notification count". (It seems I already used it earlier.)

But the strange thing is that the count remained even when changing the HumHub instance. I think it should be set to 0 when exiting an instance.

And maybe the FCM Debug page should also have the option to set the count to 0?

**Comment by PrimozRatej** [comment]
Yes, I agree the count should reset when the user exits the instance and set to new value when the user logs in to another instance,  in the way that `updateNotificationCount` is called.

**Comment by PrimozRatej** [comment]
Hey, @luke- I changed the `updateNotificationCount` functionality, so that when the user logs out of the instance we set it to 0 (badge disappears), now on the web side we would need to call the `updateNotificationCount` JS channel when the user logs in and pass in the number of the current notification count.
