### ISSUE TITLE
unable to connect because of NET::ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by jvies** [humhub/app#127]
Hi,

I've just installed the beta android app and tried to connect to Humhub installation of our associative schools.
I get the error : NET::ERR_CLEARTEXT_NOT_PERMITTED

I don't know if the issue is on the app side, or the web installation side.
The http to https redirection is ensured by traefik.

If you have any idea on how to investigate more, I can provide any needed log.

Thanks a lot

**Comment by ArchBlood** [comment]
I believe this issue has popped up before, I asked if a reverse proxy was in use for https and if the configuration was correct, by default Android will do this for unencrypted data or "cleartext", this is enabled by default for Android 9+ and webview will throw the error.

**Comment by jvies** [comment]
OK. It seems my path to images are all in pure http. I try to find why.

**Comment by jvies** [comment]
It was due to my incomplete https setting...
cf https://docs.humhub.org/docs/admin/reverse-proxy/#httpsssl-detection
