### ISSUE TITLE
Black Screen: After Installation

### ISSUE THREAD

**Issue by JK742020** [humhub/app#134]
Hey guys. Got a new mobile (Android-Version 13) installed the app and it’s not working. When opening, I see the HumHub-Logo for a short time then it gets dark and nothing else happens. With the older mobile there was no problem.

**Comment by luke-** [comment]
@JK742020 Can you please try to delete the App Data in the Android App Configuration and try again? 
e.g. https://www.samsung.com/au/support/mobile-devices/delete-application-data/

**Comment by JK742020** [comment]
Yes, it's working now. Thanks.

**Comment by PrimozRatej** [comment]
I have tested it on Android 12 (API levels 31 and 32), Android 13 (API level 33), and Android 14 (API level 34). Can't reproduce the bug. If there are currently no issues regarding this matter, I will consider it resolved.

**Comment by JK742020** [comment]
Reinstalled the app on same mobile. Problem occurred again. Cleared App data, working again.

**Comment by luke-** [comment]
@JK742020 Can you please provide steps to reproduce?
