### ISSUE TITLE
Opening the app from a link opens the page in a new "tab" of the app

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#139]
In some cases, when clicking on a link (e.g. an email from Humhub), the page opens in the app, but in a sort of new "tab" inside the app.

It seams to happen in 2 situations:
- I'm logged to the Humhub instance via an SSO
- I'm opening a link form a different Humhub instance (excepting for links from the https://community.humhub.com/ instance for which I'm redirected to the initial form allowing me to enter the Humhub instance URL)

![Screenshot_20231108_151224_com humhub app](https://github.com/humhub/app/assets/23310825/9286941d-b3ca-47c7-a078-0313750dbc27)
![Screenshot_20231108_151229_com humhub app](https://github.com/humhub/app/assets/23310825/45a12409-6d50-461f-8dd0-3f9e1dea8847)

**Comment by marc-farre** [comment]
@PrimozRatej I've also managed to open the app several times by clicking on links in email notifications.
When I look at the "opened apps", I can see multiple Humhub apps.

**Comment by PrimozRatej** [comment]
Hey @marc-farre, could you please provide me with a screenshot for this?

**Comment by marc-farre** [comment]
@PrimozRatej On this screenshot:
![Screenshot_20231110_173543_com huawei android launcher resized](https://github.com/humhub/app/assets/23310825/292c28d1-e32c-434c-b802-38f21d7ae59b)

1) is the first launch of the app on the desktop
2) is the second instance of the app, opened when clicking on a link of an email notification 

It seams that:
- When clicking on a link of the https://community.humhub.com/ instance, it opens it in a new app instance
- When clicking on a link of other instances, it opens it inside the app, but in a sort of new tab or window (see screenshot of my first comment)

If you want to try, you can create an account on the https://demo.cuzy.app/ instance here: https://www.cuzy.app/try/

**Comment by luke-** [comment]
@PrimozRatej Thanks!
@marc-farre Can you please test with v1.0.83

**Comment by marc-farre** [comment]
@PrimozRatej thanks! It makes it a lot better!

What happen when I test:
- I was connected to instance 1 and 2, but currently on instance 1
- I clicked on an email link for instance 2
- It opened the app, but I had a blank screen
- I closed the app and clicked again on the link
- It opened the app, and this time I was prompt the instance 2 URL
- I clicked on "Connect" and was properly redirected to he content
- I clicked on another email URL, for instance 1
- The app opened directly the content (no need to click on "Connect")
- I clicked again on the email URL for instance 2 (as I've done twice before)
- The app opened directly the content (no need to click on "Connect")

So first tests weren't perfect, but now it works well, I don't know why.

**Comment by marc-farre** [comment]
After a while, I had to enter again the login / password.

Another thing: if I'm on instance 1 and there is a mobile notification about instance 2, after clicking on this notification, the mobile app opens, but stay on instance 1.
Then, if I click on the email notification link, it opens correctly the instance 2.

**Comment by PrimozRatej** [comment]
Hey @marc-farre the test case sounds to me like a cache problem, can you try to clear it?
About push notifications redirects, will look into it.

**Comment by marc-farre** [comment]
> sounds to me like a cache problem

Yes, could be. Today I have no bug! I'll try later.

**Comment by PrimozRatej** [comment]
Hey @marc-farre, regarding the re-login, did you encounter any new problems?

**Comment by luke-** [comment]
Just merged the PR and released 1.0.84

**Comment by marc-farre** [comment]
> Hey @marc-farre, regarding the re-login, did you encounter any new problems?

I can still have the problem in 2 situations

1/
- Open the app in Humhub instance 1
- Close the app (if you don't close it, it's OK)
- Click on a link or a push notification of instance 2
- The app asks you to enter the URL of the instance, but is pre-filled with the URL instance 1
- If you don't pay attention to the false URL and just enter the app, it opens in a new tab

Should be solved with https://github.com/humhub/app/issues/145

2/
The problem still occurs when the FireBase Device is not registered.

Should be solved with https://github.com/humhub/fcm-push/issues/30

> About push notifications redirects, looking into it.

Thanks, it works!

**Comment by luke-** [comment]
@marc-farre I'm closing it. Let me know when it's still open.
