### ISSUE TITLE
Bypass the form URL when the app is opened from a clicked link or a push notification

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#145]
When clicking on a link (e.g. a notification email) or a push notification, the URL should be pre-filled with the base URL of the platform.
Currently the URL field is either blank, or displays the previous visited Humhub URL.

Related to https://github.com/humhub/app/issues/79

**Comment by marc-farre** [comment]
@PrimozRatej I've renamed the title, because I think that when the app is opened from a clicked link or a push notification there is no need to ask for the URL.

The problem occurs in 2 situations:
- The notification is from a Humhub instance different from the one currently opened in the app
- The FireBase Device registration is lost (happens after a certain time): see https://github.com/humhub/fcm-push/issues/30#issuecomment-1837117449 -> item 3

**Comment by marc-farre** [comment]
@PrimozRatej the problem also occurs in this situation :
1. Close the app (swiping it up in the apps switcher) 
2. Click on a notification link in an email

**Comment by marc-farre** [comment]
@PrimozRatej This issue is solved when clicking on an email notification link.
But it remains when clicking on a push notification (the native Android notification).
Thanks!

@luke- can you reopen it?

**Comment by PrimozRatej** [comment]
Hey @marc-farre this https://github.com/humhub/app/pull/206, should fix this.

**Comment by marc-farre** [comment]
@PrimozRatej I will test as soon as a new release of the app is available.

**Comment by luke-** [comment]
Just released .108

**Comment by marc-farre** [comment]
@luke- Thanks!
@PrimozRatej It works perfectly now, thanks!
