### ISSUE TITLE
Prevent page refresh when swiping down

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#147]
I had a feedback about message lost before submitting, because the user wanted to scroll up the page, but when the page is already at the top, swiping down refreshes the page.

**Comment by marc-farre** [comment]
Yes, maybe with the "Unsaved changes will be lost. Do you want to proceed?"?
https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/CoreJsConfig.php#L50

**Comment by luke-** [comment]
@marc-farre Isn the dialog triggered on mobile devices?

**Comment by marc-farre** [comment]
- Refreshing: https://github.com/humhub/humhub/issues/6708
- Messenger module: https://github.com/humhub/mail/issues/364
