### ISSUE TITLE
When switching app and returning on Humhub app, sometimes the page is black

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#148]
I could not reproduce personally.
Happens on Samsung S23 ultra, Android 14
E.g. when [the 2FA](https://marketplace.humhub.com/module/twofa/description) form is displayed, after returning back from Google Authentificator to enter the code.
But happens in other situations too.

**Comment by PrimozRatej** [comment]
Hey @marc-farre, I attempted to reproduce the bug with the following environments:

- Pixel 7, API level 33, Android 13 (Tiramisu)
- Pixel 7, API level 34, Android 14 (UpsideDownCake)
- Pixel 4, API level 33, Android 13 (Tiramisu)
- Pixel 4, API level 34, Android 14 (UpsideDownCake)

It worked fine for me. I suspect the issue might not be related to the Android version but rather the hardware of the device itself. I'm currently awaiting approval for [Samsung Remote Test Lab](https://developer.samsung.com/remotetestlab/devices/125/galaxy-s) access to test it in an exact environment. I'll report my findings once I have access.

**Comment by PrimozRatej** [comment]
Hey @marc-farre, test it on the Remote lab. All seems fine. I will be closing this issue. We can reopen if the issue resurfaces.
