### ISSUE TITLE
IOS: App Uninstall doesn't delete app data

### ISSUE THREAD

**Issue by luke-** [humhub/app#152]
https://github.com/humhub/app/assets/4736168/304f1a82-2979-49e6-bf4a-96b6cf501712

**Comment by PrimozRatej** [comment]
Solution for Android: https://stackoverflow.com/questions/57302477/flutter-not-clearing-data-even-after-installing-uninstalling-app

for iOS: https://github.com/mogol/flutter_secure_storage/issues/88
