### ISSUE TITLE
"You humhub installation does not exist"

### ISSUE THREAD

**Issue by havellab** [humhub/app#155]
Hej there,

first of all thanks for the amazing Humhub project and all efforts to build an app around it. We started using Humhub to organize our community and it is gaining quick traction, so I thought about looking into available apps. We are running 1.15.2 and I have installed the latest APK release from the Github releases but am getting a message "You humhub installation does not exist" when entering the URL of my instance. Am I missing something obvious? I Couldn't find any settings obviously related to my problem in the Humhub installation apart from push-related stuff via Firebase available as a plugin, which I would love to avoid using if anyhow possible. Is this mandatory for the app? Does anyone have an idea where I went wrong?

Many thanks

ddb

**Comment by felixhahnweilheim** [comment]
According to https://github.com/humhub/app/issues/98#issuecomment-1637649958 it seems to be mandatory.

Why don't you want to use it? Using the app without push notifications does not have so much benefits over the PWA.

**Comment by havellab** [comment]
Ah, thanks, I didn't see that hint yet. The reason we are looking at the app is that it would be less obscure than the PWA for people used to installing apps on their phone via play- or appstore. As we are trying to build a city-wide social network and thus try to onboard a lot of people with a very regular relationship towards smartphone usage, an app would have required less explanation. At least thats the theory :)
Re firebase, it's Google, and we are trying to not involve large corps into what we are doing. I will investigate a little more, maybe the lack of push also is a feature and we will just spend some time educating people about PWA and the world beyond an app.

**Comment by felixhahnweilheim** [comment]
Ok, I can totally understand that you don't want to use Google Services.
I'd recommene to install the app and don't fill out the Google field.
You can fill out the field for the HumHub push service (it's also external but HumHub is definetly not such a big player.)
As far as I understand the HumHub Push service is used for the app, Google for PWA and browser.

**Comment by felixhahnweilheim** [comment]
Even if you don't fill out anything the FCM module makes the app work.
Actually the app could be called something like  "mobile app support" at tge moment. Push notifications is only one of the tasks.

**Comment by havellab** [comment]
I unfortunately cannot seem to be able to register an account with the Humhub community, which seems to be required in order to register the Humhub push service. Registration claims to send an email which never arrives. Tried with two different mail servers on my end to no avail :-/

**Comment by ArchBlood** [comment]
> I unfortunately cannot seem to be able to register an account with the Humhub community, which seems to be required in order to register the Humhub push service. Registration claims to send an email which never arrives. Tried with two different mail servers on my end to no avail :-/

Make sure that you've also checked your spam/junk folder(s), if it's still not sent it then you probably will have to whitelist the domain that HumHub uses.

**Comment by havellab** [comment]
All mails from registration efforts have just popped in at once. Whatever anyone did, thanks a bunch!

**Comment by luke-** [comment]
Does the problem still exist?

**Comment by PrimozRatej** [comment]
If there is no problem I'm closing it for now. We can reopen if needed.
