### ISSUE TITLE
App crashes at first start

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#165]
I experiment random crashes of the app on my Huawei P30 pro Android 10.
Even on https://community.humhub.com/
It happens mainly a few seconds after clicking on "Connect" when clicking on a login field, or after login after clicking a link.
It doesn't seam to be related to what I click on because it's quite random, but it's mainly at the beginning of using HumHub.
I have this issue since many versions of the app (maybe from the beginning).

@PrimozRatej maybe I could help with ADB to have the log? Another idea?

**Comment by marc-farre** [comment]
@PrimozRatej Thanks!
I personally still have the issue with Android 10.

I renamed this issue title because I can now reproduce it every time.
@luke- Can you reopen it?

Steps to reproduce:
- Android settings -> Apps -> HumHub
- Storage -> CLEAR DATA
- Open HumHub and connect to https://community.humhub.com instance
- Click on "Got it" (the button at the bottom about cookies)
- The app crashes

**Comment by PrimozRatej** [comment]
Hey @marc-farre does this look like your device?

![image](https://github.com/humhub/app/assets/10835179/f7f5c386-3dca-4293-95f0-347a5896b0d0)

**Comment by marc-farre** [comment]
> does this look like your device?

Yes, except that mine is HUAWEI P30 pro (and not lite).

**Comment by PrimozRatej** [comment]
If you can, please, it will help a lot. I can't seem to replicate it.

**Comment by marc-farre** [comment]
@PrimozRatej Done just now

**Comment by PrimozRatej** [comment]
Thanks, I'll let you know. The crash log updates every couple of hours.

**Comment by PrimozRatej** [comment]
Hey @marc-farre, strange that your crash is not detected in the crash report on Google Play. We can enable Google Analytics for more in-depth tracking and then test this in real-time. The most annoying thing is that I really can't replicate the bug. I downloaded the exact image that the P30 Pro uses, and I could't replicate. I would say it's device-specific, but I also tested it on an actual P30 Pro (physical device), so idk anymore.

**Comment by marc-farre** [comment]
@PrimozRatej Thanks for your tests. I still think there is an issue with the app, because other apps nether crashes on my phone.

Maybe it's the same issue we had here: https://github.com/humhub/app/issues/104
And it came back again?

Do you want logcat from adb?

**Comment by PrimozRatej** [comment]
Finally able to recreate the crash, I think this is the bug in question.

[crash.txt](https://github.com/humhub/app/files/15312432/crash.txt)

**Comment by PrimozRatej** [comment]
Hey @marc-farre, I fixed it. The problem was with the underlying native web view library. Some devices had issues communicating with the new versions of Android WebView, but they have patched it now. I tested it on my P30, and the prod app no longer crashes when opening the menu dialog. This PR should fix it https://github.com/humhub/app/pull/198

**Comment by marc-farre** [comment]
@PrimozRatej Thanks, works perfectly!

@luke- If not too long to upload on the Play Store, I think this version would be great to have, as it gives a much better first experience with the app. Thanks!

**Comment by luke-** [comment]
@marc-farre Just started the 1.0.103 Release Rollout!
