### ISSUE TITLE
FR Translations

### ISSUE THREAD

**Issue by luke-** [humhub/app#168]
@marc-farre Can you please take a look here?

**Comment by marc-farre** [comment]
@luke- Done: https://github.com/humhub/app/pull/169

If needed, my wife speaks native Portuguese and can review translation for it (I can see many HumHub instances in Brazil and a few in Portugal).

**Comment by luke-** [comment]
@marc-farre Thank you for the quick translation and also for the offer. For now, I would leave the app in the 3 languages (EN, FR, DE). Should we expand here, we'll have to think about how to organize it.
