### ISSUE TITLE
When opening the app from a notification, a loading animation should replace the black screen

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#175]
1. Click on an email notification ("View online" button)
2. The HumHub app opens
3. We see for less than a second the form to enter the HumHub instance URL (renders like a flash)
4. A black screen is shown or a few seconds (sometimes up to 10 seconds)
5. The content is displayed.

Could we replace 3 and 4 with a loading animation?
It looks like a bug at the moment.

**Comment by marc-farre** [comment]
@PrimozRatej Thanks.
I don't know why, but on version 1.0.98 on Android 10 I still don't see any loading animation.
The screen is still black.

@luke- maybe this issue could be reopened.

**Comment by luke-** [comment]
FYI, just released 1.0.99

**Comment by marc-farre** [comment]
With 1.0.99 the animation works (it's very nice!) when the app is already opened.

However, it doesn't solve the black screen.

On a browser, while the page is being loaded, we have an animation on the tab:
![image](https://github.com/humhub/app/assets/23310825/1a5d9eee-4ae0-4978-b7c3-312a6b38479a)

But on the mobile app, we only see a black screen.

On this example, the black screen lasts 5 seconds (but sometimes it's longer):
![image](https://github.com/humhub/app/assets/23310825/fa77f50b-29dd-4f2c-a3fc-b587cf4b05cc)

To reproduce:
1. Click on a notification
2. The app displays the instance URL form for a short time
3. The blank screen is shown (as long as the page takes to be loaded)
4. The page is displayed
