### ISSUE TITLE
Don't show the instance URL connection form for single instance usage

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#179]
Once the instance URL submitted (on first use of the application), if the app is only used for one HumHub instance (most use cases), we shouldn't display the instance URL connection form each time the app is opened again.

If we later need to add an instance (https://github.com/humhub/app/issues/79), we can log out.

However, the instance URL connection form should still be displayed on app opening if we entered multiple instances (to have [the "Dropdown instance chooser" in development](https://github.com/humhub/app/issues/79#issuecomment-1806873020)).

**Comment by luke-** [comment]
@PrimozRatej Any idea?   The "opener" should not be shown until Logout.

**Comment by marc-farre** [comment]
@PrimozRatej Thanks.
It seems to work, but I cannot fully test because of https://github.com/humhub/app/issues/181 (in this case, it doesn't work, the form still displays, but I think that resolving this new issue should make it work).
