### ISSUE TITLE
App is opened twice after clicking on a notification link

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#181]
Steps to reproduce:
1. Install app v1.0.100
2. Open the app
3. Login
4. Switch to your email client app (don't close HumHub app)
5. View an email notification
6. Click on the "View Online" link

![Screenshot_20240514_105149 resized](https://github.com/humhub/app/assets/23310825/6ec5c227-efb4-4071-8e46-9fa601f820d8)

**Comment by PrimozRatej** [comment]
Hey @marc-farre, I tried to reproduce this a couple of times with different scenarios today, but I couldn't. Could you try it again? I think it was fixed with https://github.com/humhub/app/pull/204.

**Comment by marc-farre** [comment]
@PrimozRatej thanks for testing. Yes, it seems to be fixed (tested with v1.0.110).
