### ISSUE TITLE
Doesn't find my instance in app by IP

### ISSUE THREAD

**Issue by aarmn** [humhub/app#183]
It's a private instance with an IP only access, no domain is parked on the server, is it expected behaviour? If so any horizon for improvement? If it's unexpected I can provide my instance address for further investigation.

**Comment by PrimozRatej** [comment]
Hey @aarmn overall it should work, can you please provide me with the IP, I will take a look into it. Thank you.

**Comment by aarmn** [comment]
> Hey @aarmn overall it should work, can you please provide me with the IP, I will take a look into it. Thank you.

sure, but the deployment might be off some of the times
http://188.121.107.234

**Comment by aarmn** [comment]
Thanks! works like a charm, but a weird thing I notice is rn, is after making this instance https, still, it tries to connect to https, should we use http and forward it to https by nginx?

**Comment by marc-farre** [comment]
@aarmn Have you tried to edit the `.htaccess` file in HumHub root and to uncomment the lines after `# uncomment to force https requests`?

**Comment by aarmn** [comment]
I know we can force https with server redirect, I just wonder shouldn't it use the protocol already provided in link?
