### ISSUE TITLE
Workaround zoom into picture not available on app

### ISSUE THREAD

**Issue by JK742020** [humhub/app#184]
Because there is no possibility to just zoom into a picture by default we use a workaround with PWA and Browser which is 

1. touch picture a little longer
2. in the context menu choose "open in Browser" 

Using the android app there is no context menu appearing at all.

Solution

- Implement context menu
- best would be to have the possibility to just zoom in when using a mobile like here on github for example

**Comment by marc-farre** [comment]
@JK742020 there is a pinch-to-zoom functionality which work on the Android mobile app and web browser.

**Comment by marc-farre** [comment]
Related to https://github.com/humhub/humhub/issues/5310

**Comment by ArchBlood** [comment]
I've tested in android 12 which does not work in the app @marc-farre.

**Comment by marc-farre** [comment]
Strange. Tested on Android 10, it works for me. I'll do more tests later.

**Comment by JK742020** [comment]
Never worked with my mobile neither the versions bevor nor android 13 which is installed right now. This is the fact in the app and PWA of my network and also of the humhub-community.

**Comment by marc-farre** [comment]
@luke- I think this issue can be closed as it should be fixed by https://github.com/humhub/humhub/issues/5310#issuecomment-2121084157

**Comment by luke-** [comment]
@marc-farre Ok, then have the Core PR tested first.

But I could think that we have somehow deactivated the zoom for the app as well.

**Comment by luke-** [comment]
@marc-farre Great, thank you for testing! Then I'll close this!
