### ISSUE TITLE
APP crashes when trying to upload file in Files-Module

### ISSUE THREAD

**Issue by JK742020** [humhub/app#190]
Galaxy XCover Pro, One UI-Version 5.1, Android 13

I tried to upload a .mp4 (30,5 MB) within the Files Module and App closed three times.

Using the PWA everything works find.

**Comment by PrimozRatej** [comment]
Hey @JK742020, tnx for info, will take a look into it.

**Comment by PrimozRatej** [comment]
Hey @luke- is there a way to change max limit file size for an instance, I would like to upload 40MB file on "sometestproject12345" instance, but I get an error.

![Screenshot 2024-06-19 at 20 33 14](https://github.com/humhub/app/assets/10835179/78ab2e33-0947-479c-8117-dc38c4af54f1)

**Comment by ArchBlood** [comment]
> Hey @luke- is there a way to change max limit file size for an instance, I would like to upload 40MB file on "sometestproject12345" instance, but I get an error.
> 
> ![Screenshot 2024-06-19 at 20 33 14](https://github.com/humhub/app/assets/10835179/78ab2e33-0947-479c-8117-dc38c4af54f1)

Must first be done through php.ini then you can increase the maximum upload size.

**Comment by marc-farre** [comment]
@JK742020 this issue might be related to https://github.com/humhub/app/issues/165 which is solved in version 1.0.103.
Could you try again with this version? https://github.com/humhub/app/releases/tag/v1.0.103

**Comment by JK742020** [comment]
> @JK742020 this issue might be related to #165 which is solved in version 1.0.103. Could you try again with this version? https://github.com/humhub/app/releases/tag/v1.0.103

It works fine now. Thanks!

Is there a routine for regular users to update to the newest version without deinstalling and reinstalling?

**Comment by PrimozRatej** [comment]
Hey @JK742020, version 1.0.103 is currently in production on Play Store. You can update it as you would normally do any other app.

**Comment by JK742020** [comment]
> Hey @JK742020, version 1.0.103 is currently in production on Play Store. You can update it as you would normally do any other app.

If my settings are "update apps automatically" humhub App will be updated automatically as well?

**Comment by marc-farre** [comment]
> If my play store settings are "update apps automatically" humhub App will be updated automatically as well?

Yes
