### ISSUE TITLE
"see online" link in the Mail summary opens in the browser instead of the app

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#194]
Clicking on this link:

![image](https://github.com/humhub/app/assets/23310825/f6197151-c9fd-41d4-aa18-84d035b64c9a)

E.g. https://community.humhub.com/s/general-discussion/post/post/view?id=16700

Opens HumHub in the browser instead of the app.

App version: 1.0.100

**Comment by luke-** [comment]
@marc-farre Does the link use the "go.humhub.com" service? If not, that would probably be more of an issue for `fcm-push`, right?

**Comment by marc-farre** [comment]
@luke- Thanks, you're right!
I've opened this new issue: https://github.com/humhub/fcm-push/issues/41
