### ISSUE TITLE
Landscape mode is not available

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#208]
When the mobile device has "Auto-rotate" turned on and the mobile is turned in landscape mode, the app still displays in portrait mode.

**Comment by luke-** [comment]
At least for the opener we should keep Portrait Mode Only, as the layout is not designed for landscape.

**Comment by PrimozRatej** [comment]
We could enforce portrait mode on the opener and allow landscape mode on the webview screen.

**Comment by marc-farre** [comment]
> We could enforce portrait mode on the opener and allow landscape mode on the webview screen.

@PrimozRatej That would be awesome, especially when viewing images or video in landscape format.

**Comment by marc-farre** [comment]
@PrimozRatej Thanks!
