### ISSUE TITLE
Remove spaces in the opener URL field

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#209]
When typing a URL, Android often automatically adds a space at the end.

As this field is for a URL, we should trim entered spaces.

![image](https://github.com/user-attachments/assets/c127696a-dc62-40ed-a734-42f9a99da4a9)

**Comment by PrimozRatej** [comment]
Hey @marc-farre, did you mean to include a space at the end of the input field example, like this: 'https://community.humhub.com/dashboard_'. The underscore represents a space.

**Comment by marc-farre** [comment]
@PrimozRatej works fine now, thanks!
