### ISSUE TITLE
Notification links opens in the browser instead of the app (since 1.0.108)

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#213]
When receiving an email notification, if I click on "View Online", HumHub opens in the default browser instead of the app.
This issue occurs since version 1.0.108
Tested with https://community.humhub.com/ (I'm logged-in in the app).
The URL starts with `https://go.humhub.com?url=https%3A%2F%2Fcommunity.humhub.com%2Fnotification%2Fentry%3Fid........`

**Comment by PrimozRatej** [comment]
Hey @marc-farre, I tested the intent redirects on the community and on my demo instance, and it seems to work for me (device P30 pro). Could you please provide me with a redirect link that you were trying to use to open the app with? Thanks.

https://github.com/user-attachments/assets/29cd9b2f-6898-4816-a7fd-1525f9f0d538

https://github.com/user-attachments/assets/823e77bd-8f90-40ce-afaa-2ce3804a2a00

**Comment by marc-farre** [comment]
@PrimozRatej I've done some more tests (I also test on the P30 pro):
- Uninstalled the app
- Installed the new version 1.0.109
- Logged-in to https://community.humhub.com/
- Clicked on a link from my email client (I tested 2 different), e.g.  https://go.humhub.com/?url=https%3A%2F%2Fcommunity.humhub.com%2Fnotification%2Fentry%3Fid%3D313411%26cId%3D279598&hid=8d1f04

It still opens in the browser instead of the app.

I've checked the settings:
![image](https://github.com/user-attachments/assets/4f06a262-4700-449c-a44a-6b05201f555c)

It should ask me on which app the link should be opened.

Could you try uninstalling / reinstalling the app maybe?

Push notifications work well (the app is opened).

**Comment by PrimozRatej** [comment]
@marc-farre Strange. I repeated your use case (reinstalled an app) and it worked as expected. Then I thought that maybe you have installed the WPA version of the community instance, and that there might be some strange behavior with both apps installed. I installed the WPA version, but no, it still opens primarily with the native app. 

What were the mail clients you opened the link with?

**Comment by marc-farre** [comment]
@PrimozRatej Thanks for your investigation.
It wasn't related to the app version.
For some reason, HumHub links were configured to open by default with one of my browser.

Even uninstalling and reinstalling HumHub app didn't solve the issue. And as shown above, HumHub app was properly configured to open HumHub URLs.

But I managed to solve it by clicking here for the browser app:
![image](https://github.com/user-attachments/assets/b52721d2-e656-4c54-8432-5cfba4f19475)
