### ISSUE TITLE
Language localisation

### ISSUE THREAD

**Issue by luke-** [humhub/app#22]

**Comment by PrimozRatej** [comment]
Hey @luke-,

I've implemented the functionality. Currently, the app supports English, Spanish, and German languages. The language switcher works in default mode, so if the user has the locale set to any of the supported locales, the app will be displayed in that language. If the user overrides it within the app (e.g., having the device in German but wanting the app to show in English), the app will remember it and open in that language next time.

Currently, the Component locale switcher looks similar to the one on the official HumHub website. I haven't implemented hover-on animations, as I didn't see it as necessary for the app.

The localization files are inside the `app/lib/l18n` directory. For the German and Spanish translations, I basically just used Google Translate, so it might be a good idea for someone with knowledge of those languages to review them as well.

**Comment by PrimozRatej** [comment]
Hey @luke- , @Eladnarlea I added the French and removed Spanish.

https://github.com/humhub/app/assets/10835179/2ce9b483-4754-4c96-ac26-fd6fe4040596

**Comment by luke-** [comment]
@PrimozRatej Thank you! Looks good. I'm not sure if we need the language switcher in the long run, as we can just use the system language here like most apps. But it's great for the start and for testing the languages.

**Comment by Eladnarlea** [comment]
@PrimozRatej looking good! is it only possible to trigger the switcher on the "arrow pointing down" or does the whole section function like a button?

**Comment by PrimozRatej** [comment]
Hey @Eladnarlea hitbox is over the whole dropdown component.
<img width="386" alt="Screenshot 2024-03-15 at 07 26 21" src="https://github.com/humhub/app/assets/10835179/16351414-0800-462f-90e5-1478cc61667d">

**Comment by Eladnarlea** [comment]
@PrimozRatej great, thx!
