### ISSUE TITLE
By default, enabled "Mobile" notification types for those enabled for "Web"

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#221]
Current default notification settings:
![image](https://github.com/user-attachments/assets/de8d01bf-82f8-47af-a54a-b3d1583c435b)

I think it's quite confusing to have `Web` notifications and not `Mobile` notifications by default.
When the mobile app is installed, people doesn't understand why notifications are not working.

I suggest enabling `Mobile` notifications by default, everywhere `Web` notifications are enabled.
This way, the first experience with HumHub is better. Admins can later disable them.

**Comment by luke-** [comment]
@marc-farre Ok sounds good. Can you change this?
