### ISSUE TITLE
Page not found using app

### ISSUE THREAD

**Issue by FernandoHCFaria** [humhub/app#239]
When I log using the app I always get a message "Page not found" no matter which account I use (Admin or regular user). 
This issue don't appear if I use a normal browser. I already enabled PrettyUrls in my common.php file

![Screenshot_20241008_104526](https://github.com/user-attachments/assets/e468b1e6-6d70-46b8-89fd-becd6f26fa3b)

**Comment by marc-farre** [comment]
@FernandoHCFaria
1. What is the URL of your page (you can remove your domain from the URL)?
2. Have you got lines with a non-green dot in Administration -> Information -> Prerequisites?
3. Have you got errors in the logs? Administration -> Information -> Logging
4. What version of the mobile app are you using?
5. What version of HumHub is installed?
Thanks in advance for this information.

**Comment by FernandoHCFaria** [comment]
@marc-farre 

1. What is the URL of your page (you can remove your domain from the URL)? 
https://kinkgram.com.br

2. Have you got lines with a non-green dot in Administration -> Information -> Prerequisites? 
All is green

3. Have you got errors in the logs? Administration -> Information -> Logging 
No errors

4. What version of the mobile app are you using? 
1.0.120 (Im a beta tester since today but this issue happens since before that)

5. What version of HumHub is installed? 
1.16.2

**Comment by marc-farre** [comment]
Thanks.
If you want, you can send me login info to an account so I can test on my side (if possible an admin account), in private message: https://community.humhub.com/u/cuzy.app/home
You can use https://pwpush.com/ to send the password securely.

**Comment by FernandoHCFaria** [comment]
> Thanks. If you want, you can send me login info to an account so I can test on my side (if possible an admin account), in private message: https://community.humhub.com/u/cuzy.app/home You can use https://pwpush.com/ to send the password securely.

I just sent a private messate to you

**Comment by marc-farre** [comment]
Thanks. Just tested, it works on my side:
![image](https://github.com/user-attachments/assets/66104862-a963-489d-b095-52747865c1d7)

What phone and Android version have you got?
Can you test on another phone?

**Comment by ArchBlood** [comment]
I'd also like to ask if flushing the app cache fixes the issue as well?

**Comment by FernandoHCFaria** [comment]
@marc-farre I have a Samsung S22 and Android 14.

@ArchBlood I already did it too

And the error still here when I use the app

**Comment by marc-farre** [comment]
@FernandoHCFaria The best would be to try with another phone if you can.
On my side, your site works perfectly in the app, I can access any page, including the dashboard.
So maybe there is an issue with Android 14.
But before searching more, it would be great if you can test on another phone.
Thanks!

**Comment by FernandoHCFaria** [comment]
@marc-farre i can try with my wife's phone. He has a galaxy A52 but i think the Android version is 14 too

**Comment by FernandoHCFaria** [comment]
@marc-farre I just tried to use the app with my wife's phone. She has a Galaxy A52 and Android 14. The issue happens too

**Comment by marc-farre** [comment]
@PrimozRatej can you try this instance with Android 14 (I'll send you the credentials via private message).
I've checked, everything seems to be fine on it.
Thanks!

**Comment by marc-farre** [comment]
@FernandoHCFaria version 1.0.221 is now available in the Play Store.
Can you update the app on your mobile and tell us if the issue is fixed?
Thanks!

**Comment by FernandoHCFaria** [comment]
@marc-farre yes i noticed. I'll test it tonight and then I'll tell you if the issue was fixed.

**Comment by FernandoHCFaria** [comment]
@marc-farre I just tested the new version and it seems the issue was fixed

**Comment by marc-farre** [comment]
> @marc-farre I just tested the new version and it seems the issue was fixed

@FernandoHCFaria thanks for your feedback

@PrimozRatej FYI, your fix works well, thanks!
