### ISSUE TITLE
Some Push notifications get lost in flight mode

### ISSUE THREAD

**Issue by JK742020** [humhub/app#248]
When on flight mode only some of the push notifications sent in the time of flight mode get through when leaving flight mode. Sometimes there are notifications from the PWA but not from the APP sometimes the other way around. Sometimes there are both or non of them. It seems quite randomly.
I also placed an issue in [humhub/fcm-push](https://github.com/humhub/fcm-push/issues/55#issue-2602360577).

**Comment by marc-farre** [comment]
@JK742020 thanks. For the moment, let's keep the issue on https://github.com/humhub/fcm-push/issues/55 only.
If we find that the app is causing this issue too, we will create a new issue here.
