### ISSUE TITLE
App chrashed when opening large pdf-file from wiki

### ISSUE THREAD

**Issue by JK742020** [humhub/app#254]
A large pdf-file (85 MB) was uploaded into a wiki. I tried to open the file by clicking the pdfs name. On the bottom of the app there was displayed "Downloading" and a counter with a circle showing the status auf the download. When download was finished the app crashed. 

android version 13, UI- Version 5.1

**Comment by marc-farre** [comment]
@JK742020 What app version? See list here: https://github.com/humhub/app/releases

**Comment by JK742020** [comment]
1.0.121

**Comment by marc-farre** [comment]
@PrimozRatej an idea?

**Comment by PrimozRatej** [comment]
Hmm, we load file data as byte file in memory, maybe this is the upper limit of memory used.
@marc-farre will look into it.

**Comment by PrimozRatej** [comment]
@JK742020 the update for this fix was released in [v1.0.122](https://github.com/humhub/app/releases/tag/v1.0.122) and is live in production. Closing this issue now.
