### ISSUE TITLE
CustomPage with iframe leave the IOS App

### ISSUE THREAD

**Issue by paediG** [humhub/app#255]
On the desktop, we have embedded a sidebar widget with HTML and an iframe using the CustomPages module.
On the IOS app, it opens the URL of the iframe in the Safar browser every time the dashboard is called up, so that the HumHub app is exited. It works correctly on the Android app.

**Comment by ArchBlood** [comment]
I'd be interested to know if the same issue happens with the Codebox module as well?

**Comment by paediG** [comment]
Yes, the same issue also occurs with the Codebox module.

**Comment by PrimozRatej** [comment]
@paediG could you please give me the access to that instance, so I could replicate. mail: primozratej@gmail.com

**Comment by ArchBlood** [comment]
> @paediG could you please give me the access to that instance, so I could replicate. mail: [primozratej@gmail.com](mailto:primozratej@gmail.com)

I'd be more interested in the iframe used, as in this case it sounds more like the iframe is being restricted due to CSP violations through Safari's webview rendering. 🤔
