### ISSUE TITLE
Switch Network doesn't work

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/app#262]
I've updated to v1.1.0 and updated the FCM module in my networks. So the "Switch Network" button is shown.
When I click it, nothing happens and I can't click anything anymore.
It's like frozen but scrolling on the page still works.

(When I close the app and open again the networks overview page is shown and I can open one of my networks.)

Unfortunately, I have no debugging tools on my phone, so I don't know if there is a JS error or what is happening.

Android version 13

**Comment by marc-farre** [comment]
@felixhahnweilheim Thanks for your feedback.
You need v1.1.0: https://github.com/humhub/app/releases/tag/v1.1.0

**Comment by felixhahnweilheim** [comment]
Before 1.1.0 the button wasn't shown at all.
I've downloaded the apk from the Github release and updated the app with it.

Clearing the app cache did not help.

**Comment by marc-farre** [comment]
@felixhahnweilheim thanks.
See my private message on https://community.humhub.com/mail/mail/index?id=2701

**Comment by marc-farre** [comment]
@felixhahnweilheim We have just released version 2.1.2 which now fixes this issue. Thanks again!

**Comment by felixhahnweilheim** [comment]
Thanks! It works 👍
