### ISSUE TITLE
Test Unreachable HumHub

### ISSUE THREAD

**Issue by luke-** [humhub/app#55]
Test app behaviour when the specified and saved HumHub URL is no longer available.

**Comment by ArchBlood** [comment]
Just tested on a separate HumHub instance other than the community site, fails to load and just generates blank page.

**Comment by ArchBlood** [comment]
> Same here. I can only use the app with https://community.humhub.com/ but it doesn't work (blank page) with others Humhub instances such as https://demo.cuzy.app/ (with Firebase module) of even with an instance of a updated the develop branch. Thanks!

This is due to both of the following issues, this makes it so that only HumHub hosted instances are possible.
https://github.com/humhub/app/blob/dcd43c055a6024ea4edfb496645208006de23c79/web/manifest.json#L4

https://github.com/humhub/app/blob/dcd43c055a6024ea4edfb496645208006de23c79/lib/models/manifest.dart#L14-L20

**Comment by funkycram** [comment]
Thanks @ArchBlood !

**Comment by luke-** [comment]
@funkycram @ArchBlood If you like, you can send me your Playstore emails or Apple IDs in the Community. Then I can invite you to the test flight.

**Comment by luke-** [comment]
Do you have any idea how we can check in a reliable way if the URL entered is a HumHub instance?

- Using `manifest.json` - we could e.g. add a category `HumHub`, which indicates it is a valid HumHub installation. https://developer.mozilla.org/en-US/docs/Web/Manifest/categories - a field like `related_application` is not widely supported. https://developer.mozilla.org/en-US/docs/Web/Manifest/related_applications

- Using a  header or meta tag of the first page. We would then always have to pass this.

- Using some default endpoint e.g. `/app/probe` which determines the given URL is active or not

**Comment by ArchBlood** [comment]
> Do you have any idea how we can check in a reliable way if the URL entered is a HumHub instance?
> 
> - Using `manifest.json` - we could e.g. add a category `HumHub`, which indicates it is a valid HumHub installation. https://developer.mozilla.org/en-US/docs/Web/Manifest/categories - a field like `related_application` is not widely supported. https://developer.mozilla.org/en-US/docs/Web/Manifest/related_applications
> 
> - Using a  header or meta tag of the first page. We would then always have to pass this.
> 
> - Using some default endpoint e.g. `/app/probe` which determines the given URL is active or not 
> 
> 

The only thing I can think of is using the dashboard as an endpoint, but doing this won't help those using customized landing pages. 🤔

Overall the `category` option isn't a bad idea here either.

**Comment by luke-** [comment]
@ArchBlood I'm not sure I'm understanding you correctly. `api.humhub.com` does not collect or receive base URLs from any installations. Therefore we could not validate if this is correct.

**Comment by ArchBlood** [comment]
> @ArchBlood I'm not sure I'm understanding you correctly. `api.humhub.com` does not collect or receive base URLs from any installations. Therefore we could not validate if this is correct.

That's not exactly what I mean, what I mean is there is a way of searching for the `baseUrl` variable itself not a collection of the data, so when a call is made to the API it searches for the variable `baseUrl` which is then validated by the HumHub instance through the setting `Base URL`.

**Comment by luke-** [comment]
@PrimozRatej The most reliable solution would be:

- Check Status Code is 200 (+ Follow redirects)
-  The response source content must contain `humhub.modules.ui.view`

**Comment by PrimozRatej** [comment]
In the scope of this task, I moved the logic of how to obtain the URI or HumHub instance to a separate controller that the Opener is now using it. There are 2 main methods that I use to determine if the URL is a HumHub instance. First is a `findManifest()` and `checkHumHubModuleView(Uri uri)`.  `findManifest()` checks all the URI `pathSegments` trying to find `manifest.json` on any of the levels. When a manifest is found we don't know for sure if this manifest is a HumHub manifest this part is checked by checkHumHubModuleView(Uri uri) takes a baseUrl calls it and checks if the returned HTML contains `'humhub.modules.ui.view'`

I also added a test for findManifest functionality:
https://github.com/humhub/app/blame/a788b5b586d391265e0d4b9ace87a6e9b0a4c965/test/opener_test.dart#L24-L35

**Comment by ArchBlood** [comment]
Looks like the latest changes have broken everything.

### Any HumHub even HumHub hosted
![Screenshot_20230612-075943.png](https://github.com/humhub/app/assets/35392110/debb5d81-7fdc-44a2-b510-3c14e6779ea3)

![Screenshot_20230612-080654.png](https://github.com/humhub/app/assets/35392110/a4fd206a-72d4-40bb-a5b5-6fa788a8d32d)

I've tested the following apks

- [x] v1.0.52/app-arm64-v8a-release.apk
- [x] v1.0.52/app-armeabi-v7a-release.apk
- [x] v1.0.52/app-x86_64-release.apk

Don't own a compatible phone but from the last two tests O can safely say this version probably doesn't work either.

**Comment by funkycram** [comment]
Thanks @PrimozRatej 
I've tested the latest version v1.0.52 with Humhub 1.14.2 (https://demo.cuzy.app/) and I still have the blank screen after clicking on the "Connect" button.

Then I tested the Community instance (https://community.humhub.com/) and I also have a blank screen (it was working before).

**Comment by ArchBlood** [comment]
Could this be the issue?

https://github.com/humhub/app/blob/master/web/manifest.json#L4

**Comment by ArchBlood** [comment]
I look forward to testing! :smile:

**Comment by funkycram** [comment]
Thanks @PrimozRatej , I think you can close the issue, it's fine!
