### ISSUE TITLE
Check Headers

### ISSUE THREAD

**Issue by luke-** [humhub/app#56]
I've added a header test page here: https://sometestproject12345.humhub.com/mobile-app/index

For some reason the app headers are not visible either on full page reload or on pjax (partial) page load. Can you please take a look here?

---

Also, a new header `x-humhub-app-ostate` would be good, which indicates whether the opener is hidden or not. If set to value `1`,  the opener is hidden.

 With this we could handle the case: not logging into HumHub and opener dialog is hidden/disabled. Then we could trigger a `hideOpener` here from HumHub side.

---

**Comment by PrimozRatej** [comment]
There was a bug when appending the headers on Ajax request. fix it and added `x-humhub-app-ostate` which is 1 if Opener is hidden.

![image](https://user-images.githubusercontent.com/10835179/221374033-d31ac6fa-cfae-4642-8008-5c96f81435ea.png)

**Comment by luke-** [comment]
@PrimozRatej Thanks. let me know when i should merge it.
