### ISSUE TITLE
Improve URL Detection Input 

### ISSUE THREAD

**Issue by luke-** [humhub/app#60]
Would be great if in the opener dialog also accepts URLs like: 

- `https://sometestproject12345.humhub.com/dashboard` 
- `https://sometestproject12345.humhub.com/user/auth/login`

**Comment by PrimozRatej** [comment]
Is it reasonable to assume that `sometestproject12345.humhub.com/dashboard` is also a valid format? It would be more convenient for the user if they didn't have to type the `https://` every time.

**Comment by luke-** [comment]
That would be good, but we must handle that it could also run under `http://`. (Maybe some autodetection?)

Also, HumHub could be installed in a subdirectory. e.g. https://example.com/humhub

**Comment by PrimozRatej** [comment]
I was thinking that if the user does not provide the protocol, we assume that it's `https`. If the user does provide a protocol, we override this assumption. Regarding installations in subdirectories, I don't see a problem as long as the `manifest.json` exists at the specified URL.

**Comment by luke-** [comment]
Ok that sounds good.

Problem could be, when a user provide `https://example.com/humhub/humhub/dashboard`. We should try to find the root URL in following order:
1. https://example.com/humhub/humhub/manifest.json
2. https://example.com/humhub/manifest.json
3. https://example.com/manifest.json

**Comment by PrimozRatej** [comment]
Acceptable URLs:
 - https://sometestproject12345.humhub.com/dashboard/something/something/
 - https://sometestproject12345.humhub.com/dashboard/something/something
 - sometestproject12345.humhub.com/dashboard/something/something
 - sometestproject12345.humhub.com
 - sometestproject12345.humhub.com/dashboard///
 - sometestproject12345.humhub.com/dashboard//something/
 - sometestproject12345.humhub.com/dashboard///manifest.json

We iterate through a `url.pathSegments` till we found and manifest.json

**Comment by luke-** [comment]
@PrimozRatej Great, thats a nice solution
