### ISSUE TITLE
OAuth/External Auths broken

### ISSUE THREAD

**Issue by ArchBlood** [humhub/app#63]
Just tested the latest version and it seems that OAuths are throwing an invalid Auth state parameter.

### Tested OAuths
- [x] GitHub

**Comment by luke-** [comment]
Hmmm, currently, external authentication methods are broken because we open all non-HumHub URLs in the browser.

**Comment by ArchBlood** [comment]
A possible fix would be using the static page method, although I'm not very experienced in the method and testing would need to be done here. 🤔

- https://itnext.io/flutter-web-oauth-authentication-through-external-window-d890a7ff6463

**Comment by luke-** [comment]
@PrimozRatej You can test the behavior on our community https://community.humhub.com with e.g. GitHub Login.

Possible solutions here could be:

1. Only open external URLs in the browser as soon as the `opener` state is set to hidden. Until then simply in the app. 
2. Allow only External URLs from specific referer sites (e.g. login). Here is the question, how do we identify such referer sites.
3. Collect a list of allowed external sites and provide this list to the app e.g. via manifest. On HumHub backend side we would need to clarify how to create this list. (Automatically or Manually)

For now, I would suggest to start with solution 1. as it is the easiest to implement.

**Comment by profzelonka** [comment]
Looking forward to testing external sites once this is resolved! Is there a way to bypass the restriction for the time being?

**Comment by PrimozRatej** [comment]
When testing external Auth methods I came across a bug on the "Sign in / up" popup. Once the popup is opened then closed and opened again the dropdown doesn't work.

<img width="679" alt="Screenshot 2023-06-11 at 15 42 09" src="https://github.com/humhub/app/assets/10835179/f1c2d4fe-06a5-481d-9f5c-b9524ed3ca11">

**Comment by luke-** [comment]
@PrimozRatej Thanks. I think we can't whitelist urls here because many sites also use custom login providers.

Here for example an option with SAML as login. 
https://staff.humhub.org/

Apps like Twitter use an integrated browser view for links. 
Could we use something like that?

**Comment by PrimozRatej** [comment]
I looked into it and it could be possible. It would require the use of `InAppBrowser` I see 2 cases here:
1. User wants to log in with an external auth provider. 
- The external auth URL is called. 
- User goes through the login process.
- The user is redirected back to the primary web view. when the callback is called.

2. All the external websites would also be opened in this `InAppBrowser`

**Comment by PrimozRatej** [comment]
Implemented just like explained [:point_up:](https://github.com/humhub/app/issues/63#issuecomment-1602065715)

We close the InAppBrowser when the redirect matches the base URL from the manifest. and use the redirect URL inside the primary WebView. Tested on Comunity and [My Test Instance](https://sometestproject12345.humhub.com/) works as expected.

**Comment by luke-** [comment]
@PrimozRatej Nice, sounds very good! 
When we trigger the InAppBrower? Will the InAppBrowser now be opened for all URLs?

**Comment by luke-** [comment]
@PrimozRatej Thanks, the solution works very good!

**Comment by PrimozRatej** [comment]
> @PrimozRatej Nice, sounds very good! When we trigger the InAppBrower? Will the InAppBrowser now be opened for all URLs?

It would open for all noninstance URLs, So if the origin URL that we want to open is not the same as the origin URL of the current manifest.

**Comment by ArchBlood** [comment]
@luke- I believe this should be reopened due to the Google OAuths client;

![Screenshot_20231129-074120.png](https://github.com/humhub/app/assets/35392110/ab1e0b23-77ec-41eb-b550-addcc48c5be2)

**Comment by marc-farre** [comment]
@PrimozRatej it seams that Google requires a browser user agent known to them.
