### ISSUE TITLE
Messenger module not working in app

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/app#75]
Testing the app (v1.0.51) on Android with community.humhub.com

Open the mail/message dropdown and click on a chat.

I receive only the title "Conversations", the rest of the screen is grey and "An unexpected error occured".

In the browser and web app everything works fine.

(Android version 13)

**Comment by ArchBlood** [comment]
Seems to also be an issue on Android 12 using v1.0.50

**Comment by funkycram** [comment]
I think it's related to https://github.com/humhub/app/issues/82

**Comment by luke-** [comment]
Yes, fixed here: https://github.com/humhub/app/issues/82
