### ISSUE TITLE
Don't ask for the Humhub instance URL on app close

### ISSUE THREAD

**Issue by funkycram** [humhub/app#87]
If the app is closed, when opening it back later, you see the form field to enter the Humhub instance URL.
It's pre-field and you don't need to enter your login/password, so it's not so bad.

But I suggest to directly enter in Humhub when opening the app.

And to have the possibility to change the Humhub instance URL, I suggest 2 methods (I think we need both or at least the second one):
- Show the form on logout
- On Humhub, add a special button displaying only when Humhub is running in the app, allowing to quit Humhub and show the form, and later to switch to another instance (when https://github.com/humhub/app/issues/79 is done)

**Comment by luke-** [comment]
@funkycram When the FCM Push module is installed, the behavior changes.

- After successful login, the app always opens the last HumHub URL (even after Close).
- On logout, this is reset and the URL dialog is displayed.

https://github.com/humhub/fcm-push/blob/master/Events.php#L91-L97

I am still a little unsure whether I should integrate this in the FCM Push module or directly in the core.

**Comment by funkycram** [comment]
@luke- OK, thanks.
So it must be related to the issue https://github.com/humhub/app/issues/86 because on the tested instance FCM Push is installed and configured.

**Comment by ArchBlood** [comment]
When I tested the app it doesn't destroy the session or return to the form after closing so I'm not sure about this unless the cache isn't being stored correctly.

The form already shows on logout, or am I mistaken here? Or at least this happens for me anyway.

I personally like the idea of being able to swipe to return to the form, but currently doing this only asks if you're sure you want to close the app.

All my tests were done with the community site.

**Comment by funkycram** [comment]
You're right. It does work well on the Community instance. It's due to FCM Push module not working anymore on my instance. See https://github.com/humhub/fcm-push/issues/23
