### ISSUE TITLE
Silent FlutterChannel `registerFcmDevice` output 

### ISSUE THREAD

**Issue by luke-** [humhub/app#88]
When HumHub sents `registerFcmDevice` via the Flutter Channel, the Mobile App performs a POST Request which outputs a Json Status code.

Currently this Status Code is shown in the WebView. The Result should not shown inside the webview.

![flutter](https://github.com/humhub/app/assets/4736168/1099033a-66e7-40b1-a341-b45db623067e)

**Comment by luke-** [comment]
Maybe we could add a new parameter `silent`.

**Comment by luke-** [comment]
@PrimozRatej Thanks, I've just tested the PR but it seems that now the POST request isn't executed at all. Can you please check?

**Comment by luke-** [comment]
@PrimozRatej Just tested the latest PR, seems the request is still not performed: https://github.com/humhub/app/pull/91

**Comment by PrimozRatej** [comment]
@luke-  Fixed this one, there is one small thing If you want to see if the token was successfully registered, you need to reload the page because the request is called in a separate webView instance so that it does not affect the main one.
